--- 
title: 'Zero-inflated models: the devil in the tails' 
author: "Timothy Daley" 
date: "7/9/2019" 
abstract: "Zero-inflated models can sometimes suck
really bad" 
output: html_document 
---


I will begin as many statistics papers do with a quote from George Box, "All models are wrong, but some are useful" (box1976science).  There is currently a discussion on the "correctness" on the assumption of zero-inflation in single cell data (hicks2017missing, risso2018general, svensson2019droplet, and townes2019feature).  I believe that this discussion misses the point.  We should instead be talking about the utility of the models.  Any specific model is going to be wrong in some way or another.  The question then becomes whether the model is sufficiently useful in spite of its incorrectness. 

In this paper we illustrate a specific and peculiar issue in zero-inflated models.  This is their dependence on specifying the correct model.  If the incorrect model is chosen, then the inferences of a zero-inflated model can be wildly wrong.  This is because the zero-inflation is equivalent to estimating the number of missing or unsampled genes (deng2019molecular).  There is a long literature in estimating the missing number of species in a sampling experiment, with most of the applications in estimating the number of missing species (fisher1943relation, bunge1993estimating, bunge2014estimating).  We can take a few lessons from this literature.  First, estimating the number of missing species is a very hard problem.  The missing species are necessarily the rarest and least abundant species.  It's difficult to rule out the possibility that there are a large number of missing species at very low abudance.  This so-called length bias makes inference difficult and can lead to arbitrarily large risk in estimating the missing species (if the number species can be infinite, in our case the number of genes is bounded but the risk can still be extremely large) (johndrow2016estimating).  

Consider the following situation.  We observe the following counts from a single cell, with j equal to count and n_j equal to the number of genes with that count:

|  j  |  1  |  2  |  3  |  4  |  5  |  6  |  8  |  10  |  15 | 26 |
|-----|-----|-----|-----|-----|-----|-----|-----|------|-----|----|
| n_j | 323 |  30 |  10 |  1  |  3  |  1  |  1  |   1  |   1 |  1 |
